//!!!DO NOT EDIT THIS FILE (AUTOGENERATED FROM config.cmake)!!!

// Include HAL library
#include "MCXA142.h"

// Include the EDF framework
/* #undef USE_EDF_FRAMEWORK */
#ifdef USE_EDF_FRAMEWORK
#include "edf.h"
#include "global_signals.h"
#endif

// Firmware version
#define PROJECT_VERSION_STR   "v1.0.0-rc.0"
#define PROJECT_VERSION_MAJOR 1
#define PROJECT_VERSION_MINOR 0
#define PROJECT_VERSION_PATCH 0
#define PROJECT_VERSION_TWEAK 0

// if the CMake variable USE_FREERTOS is set to ON or TRUE.
/* #undef USE_FREERTOS */

// if the CMake variable USE_QPC is set to ON or TRUE.
#define USE_QPC
#ifdef USE_QPC
#include "global_signals.h"
#include "qpc.h"
#endif
